project:
  type: website

website:
  title: rahuldave
  navbar:
    left:
      - href: posts.qmd
        text: Posts
      - href: til.qmd
        text: TIL
      - href: collections.qmd
        text: Collections
      - href: about.qmd
        text: About

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    reference-location: margin
    citation-location: margin
    csl: journal-of-neurochemistry.csl
    include-before-body: ads.html
