project:
  type: website

website:
  title: rahuldave
  navbar:
    left:
      - href: posts.qmd
        text: Posts
      - href: til.qmd
        text: TIL
      - href: collections.qmd
        text: Collections
      - href: about.qmd
        text: About

format:
  html:
    theme:
      light: styles/modern-light.scss
      dark: styles/modern-dark.scss
    toc: true
    reference-location: margin
    citation-location: margin
    csl: journal-of-neurochemistry.csl
    include-in-header: includes/fonts.html
    include-after-body:
      - includes/brand-icon.html
    include-before-body:
      - ads.html
      - includes/theme-toggle.html
